base_url = "https://sudo-prem.github.io"
title = "sudo-log"
description = "Code and Curiosity"
default_language = "en"
theme = "serene"
output_dir = "public"
compile_sass = true
minify_html = false
build_search_index = false
generate_feeds = false
feed_filenames = ["feed.xml"]
taxonomies = [{ name = "tags" }, { name = "categories" }]

[markdown]
render_emoji = true
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false
github_alerts = true

[markdown.highlighting]
style = "class"
light_theme = "github-light"
dark_theme = "github-dark"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]
nav = [
	{ name = "Work", path = "/work" },
	{ name = "Resume", path = "/resume" },
	{ name = "Picks", path = "/picks" }
]
name = "Premnaath Varadharajan"
handle = "sudo-prem"
handle_url = "https://github.com/sudo-prem"
bio = "🌴 On vacation"
avatar = "img/misc/avatar.webp"
links = [
    { name = "Email", icon = "email", url = "mailto:premnaathvaradharajan@gmail.com" },
    { name = "GitHub", icon = "github", url = "https://github.com/sudo-prem" },
    { name = "LinkedIn", icon = "linkedin", url = "https://linkedin.com/in/premnaath" },
    { name = "Twitter", icon = "twitter", url = "https://x.com/sudo_prem" },
]
blog_section_path = "/posts"
back_link_text = "Back"
color_scheme = "auto"
footer_copyright = "© 2026 Premnaath Varadharajan"
footer_credits = false
not_found_error_text = "404 Not Found"
not_found_recover_text = "« back to home »"
reaction = false
reaction_align = "right"
reaction_endpoint = "https://example.com/api/reaction"
